version: "3"

services:
  config_service:
    build:
      context: config_service/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - 8000
    environment:
      SPANNER_EMULATOR_HOST: "spanner:9010"
  monitor_service:
    build:
      context: monitor_service/
      dockerfile: Dockerfile
    # ports:
    #   - "8000:8000"
    environment:
      SPANNER_EMULATOR_HOST: "spanner:9010"
  spanner:
    image: gcr.io/cloud-spanner-emulator/emulator
    ports:
      - "9010:9010"
      - "9020:9020"
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - .:/workspace
      - vscode-extensions:/home/vscode/.vscode-server/extensions
    env_file:
      - .env
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
volumes:
  vscode-extensions: